### ISSUE TITLE
Where to get the dataset from? Cannot understand without the Mini_Dataset folder. 

### ISSUE THREAD

**Issue by shailja-11** [wangyi111/Bachelor-thesis#5]

**Comment by wangyi111** [comment]
Hi @shailja-11, sorry for the late reply. This repository is only demos. To play with, there are some public building extraction datasets you can easily get and try, e.g. https://www.isprs.org/education/benchmarks/UrbanSemLab/default.aspx

**Comment by wangyi111** [comment]
I may consider reimplementing the codes at some point and bring full details back. thanks for interest in this repo!
